server:
  port: 38291

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: Authorization
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: random-32
  # 是否输出操作日志
  is-log: true
  jwt-secret-key: 

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/javatemplate?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ${MYSQL_PASSWORD}
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 127.0.0.1
    port: 6379
    client-type: jedis
    password: ${REDIS_PASSWORD}
    database: 0
    jedis:
      pool:
        max-wait: 3000ms
  cache:
    redis:
      time-to-live: 1800000
  data:
    #    mongodb:
    #      #      uri: mongodb://localhost/tcm
    #      host: 127.0.0.1
    #      port: 27017
    #      database: javatemplate
    #      auto-index-creation: true
    #      #      transactionEnabled: false
    #      username: root
    #      password: ${MONGODB_PASSWORD}
    #      authentication-database: admin
    mongodb:
      #      uri: mongodb://localhost/tcm
      host: 127.0.0.1
      port: 27017
      database: javatemplate
      auto-index-creation: true


mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  # 设置别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: com.guochenxu.javatemplate.entity
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

#小程序配置
wx:
  miniapp:
    configs:
      - appid:
        secret:
        msgDataFormat: JSON


# 阿里云配置
aliyun:
  sms:
    access-key-id:
    access-key-secret:
    endpoint: dysmsapi.aliyuncs.com
    verify-code-config:
      sign-name:
      template-code:
  oss:
    access-key-id: key
    access-key-secret: secret
    endpoint: endpoint
    region: regoin
    bucket-name: name
    base-url: url

logging:
  file:
    path: ./dev-logs
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level ${PID} --- [%t] [traceId=%X{traceId}] [userId=%X{userId}] %clr(%logger{39}.%method:%line){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}" # 控制台日志格式
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level ${PID} --- [%t] [traceId=%X{traceId}] [userId=%X{userId}] %clr(%logger{39}.%method:%line){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"

redisson:
  addr: redis://127.0.0.1:6379
  password: ${REDIS_PASSWORD}
  db: 0
  connect-pool-size: 10
  connection-minimum-idle-size: 4
